"""AgentState is the single object every node in the graph reads from and
writes back to."""

from typing import TypedDict

class AgentState(TypedDict):
    task : str                  # user's input request/task
    current_step : str          # which node last touched the state
    result : str                # the agent's response/output for this turn
    plan : list[str]            # list of plan by planner node
    retrieved_context : list[str]
    generated_code : str        # code generated by coder node
    execution_success : bool    # True if the sandboxed code ran without error
    execution_stdout : str      # captured stdout from the sandbox
    execution_stderr : str      # captured stderr from the sandbox
    execution_timed_out : bool  # True if the sandbox killed the process on timeout
    blocked : bool              # input validation result and code scanner(guardrails)
    blocked_reason : str        # reason if input or code is not valid
    retry_count : int           # count of no. of times a code is reflected
    reflection_feedback : str   # error feedback generated by llm
    